name: tp_media
description: "Flutter common package by TP MEDIA. Support Admob to show ads, RevenueCat to show Paywall and handle In app purchase."
version: 0.0.4
homepage: https://github.com/thienphan1996/tp_media.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.20.2

  google_mobile_ads: ^6.0.0

  app_tracking_transparency: ^2.0.6+1

  purchases_flutter: ^9.8.0
  purchases_ui_flutter: ^9.8.0
  flutter_secure_storage: ^9.2.4

  lottie: ^3.3.2

  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/