name: tp_media
description: "Flutter monetization package by TP MEDIA"
version: 0.0.2
homepage: https://github.com/thienphan1996/tp_media_flutter.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.19.0

  google_mobile_ads: ^6.0.0

  app_tracking_transparency: ^2.0.3

  purchases_flutter: ^9.3.0
  purchases_ui_flutter: ^9.3.0
  flutter_secure_storage: ^9.2.4

  lottie: ^3.3.0

  fluttertoast: ^8.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/